DROP TABLE IF EXISTS posts;


create TABLE posts(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title NEXT NOT NULL,
    content TEXT NOT NULL
);